### ISSUE TITLE
madmaxWMFU: prs-2019-p2p

### ISSUE THREAD

**Issue by madmaxWMFU** [kottans/frontend-2021-homeworks#420]
## frontend-2019-p2p: ##
Hooli-style Popup - [#37](https://github.com/kottans/frontend-2019-p2p/pull/37)
JS DOM - [#52](https://github.com/kottans/frontend-2019-p2p/pull/52)
JS pre-OOP - [#55](https://github.com/kottans/frontend-2019-p2p/pull/55)
JS OOP - [#66](https://github.com/kottans/frontend-2019-p2p/pull/66)
JS post-OOP - [#68](https://github.com/kottans/frontend-2019-p2p/pull/68)
Memory Pair Game - [#70](https://github.com/kottans/frontend-2019-p2p/pull/70)
Friends App - [#101](https://github.com/kottans/frontend-2019-p2p/pull/101)

**Comment by OleksiyRudenko** [comment]
Confirmed
