### ISSUE TITLE
chris-voitova: PRs from p2p repo

### ISSUE THREAD

**Issue by chris-voitova** [kottans/frontend-2021-homeworks#422]
Hooli-style Popup - [kottans/frontend-2019-p2p#40](https://github.com/kottans/frontend-2019-p2p/pull/40)
Building a Tiny JS World - [kottans/frontend-2019-p2p#152](https://github.com/kottans/frontend-2019-p2p/pull/152)

**Comment by OleksiyRudenko** [comment]
Confirmed
