### ISSUE TITLE
dafen173: PRs from p2p repo

### ISSUE THREAD

**Issue by dafen173** [kottans/frontend-2021-homeworks#423]
[JS DOM](https://github.com/kottans/frontend-2019-p2p/pull/95)
[pre-OOP](https://github.com/kottans/frontend-2019-p2p/pull/124)
[OOP exercise](https://github.com/kottans/frontend-2019-p2p/pull/144)
[Memory pair game](https://github.com/kottans/frontend-2019-p2p/pull/161)
[Frogger game](https://github.com/kottans/frontend-2021-homeworks/pull/397)
[Pop-up](https://github.com/kottans/frontend-2021-homeworks/pull/429)

**Comment by OleksiyRudenko** [comment]
Confirmed

**Comment by OleksiyRudenko** [comment]
Closing this as the submissions are accounted for in https://github.com/kottans/frontend-2021-homeworks/blob/main/stats/pr-stats.md
